### ISSUE TITLE
Broken highlighting at the start of declarations

### ISSUE THREAD

**Issue by svanimpe** [jtbandes/swift-tmlanguage#13] opened 2023-12-18 06:43 UTC
A recent update seems to have broken syntax highlighting at the start of declarations. Here are some examples from https://github.com/vapor/vapor/blob/main/Sources/Vapor/Routing/Route.swift:

<img width="526" alt="Screenshot 2023-12-18 at 07 39 40" src="https://github.com/jtbandes/swift-tmlanguage/assets/1496250/c5279f60-c93f-4b34-9e52-000713d9521e">

<img width="386" alt="Screenshot 2023-12-18 at 07 39 50" src="https://github.com/jtbandes/swift-tmlanguage/assets/1496250/f6aa6bfd-9bf0-4a5e-b9b8-b7052e294294">

and from https://github.com/vapor/vapor/blob/main/Sources/Vapor/Routing/Routes.swift:

<img width="585" alt="Screenshot 2023-12-18 at 07 40 28" src="https://github.com/jtbandes/swift-tmlanguage/assets/1496250/1bd450b2-3573-42f6-b7ac-a2380940ab56">

<img width="294" alt="Screenshot 2023-12-18 at 07 40 35" src="https://github.com/jtbandes/swift-tmlanguage/assets/1496250/cbe11865-04e4-4f53-b7ce-5411fd815edb">

**Comment by jtbandes** [comment] 2024-01-02 21:43
This looks to be a duplicate of #10 which I believe is caused by https://github.com/github-linguist/linguist/issues/6668. You can follow that issue if you're interested in tracking the investigation.

**Closed by jtbandes** 2024-01-02 21:43 UTC
