### ISSUE TITLE
Highlighting breaks after multiple protocol inheritance and with @main

### ISSUE THREAD

**Issue by ktoso** [jtbandes/swift-tmlanguage#12] opened 2023-12-18 01:55 UTC
In the following file at the bottom: https://github.com/apple/swift/pull/68861/files

The coloring seems to break after a few protocols are listed in the inheritance part of a declaration:

![image](https://github.com/jtbandes/swift-tmlanguage/assets/120979/2ae8f6b7-c74b-4621-806f-304ca0aaedcc)

Similarly the `@main strut Main` coloring also breaks all the way until the code comment

**Comment by jtbandes** [comment] 2024-01-02 21:43
This looks to be a duplicate of #10 which I believe is caused by https://github.com/github-linguist/linguist/issues/6668. You can follow that issue if you're interested in tracking the investigation.

**Closed by jtbandes** 2024-01-02 21:43 UTC

**Comment by ktoso** [comment] 2024-01-03 06:22
I see, thanks for cross referencing!
